COLUMN_RENAME_VENTE={
    'vente_id': 'VenteID',
    'CodeCommune_section': 'SectionCadastraleID',
    'Date mutation': 'DateVente',
    'Valeur fonciere': 'ValeurFonciere',
    'Type de voie': 'TypeVoie',
    'No_voie' : 'NumeroVoie', 
    'Voie': 'Voie', 
    'Code postal': 'CodePostal',
    'Commune': 'Commune',
    'Surface reelle bati': 'SurfaceReelle',
    'Nombre pieces principales': 'NombrePiece',
    'nb_dependances': 'NombreDependance',
    'latitude': 'Latitude',
    'longitude': 'Longitude'
}


REMPLACEMENTS_QUARTIER = {
    'Odeon': 'Odéon',
    'Arts-et-Metiers': 'Arts-et-Métiers',
    'Javel 15Art': 'Javel',
    "St-Germain-l'Auxerrois":"Saint-Germain-l'Auxerrois"
}

COLUMN_RENAME_LOYER={
    'annee': 'Annee',
    'nom_quartier': 'Quartier',
    'piece': 'NombrePiece'
}

COLUMN_RENAME_ESPACEVERT={
    'nsq_espace_vert': 'EspaceVertID',
}

COLUMN_RENAME_BOIS={
    'nsq_espace_vert': 'BoisID',
    'nom_ev': 'NomBois',
    'poly_area': 'SurfaceBois'
}

COLUMN_RENAME_EV={
    'nsq_espace_vert': 'EspaceVertID',
    'nom_ev': 'NomEspaceVert',
    'type_ev': 'TypeEspaceVert',
    'categorie': 'CategorieEspaceVert',
    'adresse_codepostal': 'CodePostal',
    'poly_area': 'SurfaceEspaceVert'  
}


DISTANCE_VENTE = 200

DISTANCE_BOIS = 200


quartier_section_commune = {
    "Saint-Germain-l'Auxerrois" : {"sections": ['AB', 'AC', 'AD', 'AE', 'AF', 'AG', 'AH',
                                  'AI', 'AJ', 'AK', 'AL', 'AM', 'AN'], "commune": "101"},
    "Halles": {"sections": ['AR', 'AQ', 'BE', 'AP', 'AS', 'AT', 'AO'], "commune": "101"},
    "Palais-Royal": {"sections": ['AW', 'AX', 'AV', 'AU'], "commune": "101"},
    "Place-Vendôme": {"sections": ['BC', 'AZ', 'BD', 'AY'], "commune": "101"},
    "Gaillon": {"sections": ['AB', 'AC', 'AD'], "commune": "102"},
    "Vivienne": {"sections": ['AG', 'AF', 'AE'], "commune": "102"},
    "Mail": {"sections": ['AH', 'AI', 'AJ', 'AK'], "commune": "102"},
    "Bonne-Nouvelle": {"sections": ['AO', 'AP', 'AM', 'AL', 'AN'], "commune": "102"},
    "Arts-et-Métiers": {"sections": ['AC', 'AB', 'AF', 'AE', 'AD'], "commune": "103"},
    "Enfants-Rouges": {"sections": ['AG', 'AH', 'AJ', 'AI', 'AK'], "commune": "103"},
    "Archives": {"sections": ['AQ', 'AP', 'AL', 'AM', 'AN', 'AO'], "commune": "103"},
    "Sainte-Avoie": {"sections": ['AV', 'AS', 'AR', 'AU', 'AT'], "commune": "103"},
    "Saint-Merri": {"sections": ['AB', 'AC', 'AD', 'AE', 'AF', 'AG'], "commune": "104"},
    "Saint-Gervais": {"sections": ['AH', 'AI', 'AN', 'AJ', 'AM', 'AK', 'AL'], "commune": "104"},
    "Arsenal": {"sections": ['AO', 'AP', 'AQ', 'AR', 'AT', 'AS'], "commune": "104"},
    "Notre-Dame": {"sections": ['AU', 'AV', 'AX', 'AW', 'AY', 'AZ'], "commune": "104"},
    "Saint-Victor": {"sections": ['AB', 'AC', 'AD', 'AE', 'AF', 'AG', 'AH', 'AI', 'AJ'], "commune": "105"},
    "Jardin-des-Plantes": {"sections": ['AK', 'AL', 'AM', 'AN', 'AO', 'AP', 'AQ', 'AR',
                           'AS', 'AT', 'AU', 'AV'], "commune": "105"},
    "Val-de-Grace": {"sections": ['AW', 'AX', 'AY', 'AZ', 'BC', 'BD', 'BE', 'BF', 'BG',
                     'BH', 'BI'], "commune": "105"},
    "Sorbonne": {"sections": ['BJ', 'BK', 'BL', 'BM', 'BN', 'BO', 'BP', 'BQ'], "commune": "105"},
    "Monnaie": {"sections": ['AB', 'AC', 'AD', 'AE', 'AF'], "commune": "106"},
    "Odéon": {"sections": ['AG', 'AH', 'AI', 'AJ', 'AK', 'AL', 'AM', 'AN', 'AO', 'AP',
              'AQ'], "commune": "106"},
    "Notre-Dame-des-Champs": {"sections": ['AR', 'AS', 'AT', 'AU', 'AV', 'AW', 'AX', 'AY',
                              'AZ', 'BC', 'BD', 'BE', 'BF', 'BG', 'BH'], "commune": "106"},
    "Saint-Germain-des-Prés": {"sections": ['BI', 'BJ', 'BK', 'BL', 'BM', 'BN'], "commune": "106"},
    "Saint-Thomas-d'Aquin": {"sections": ['AB', 'AC', 'AD', 'AE', 'AF', 'AG', 'AH', 'AI',
                             'AJ', 'AK', 'AL', 'AM', 'AN', 'AO'], "commune": "107"},
    "Invalides": {"sections": ['AP', 'AQ', 'AR', 'AS', 'AT', 'AU', 'AV', 'AW', 'AX', 'AY',
                              'AZ', 'BC', 'BD', 'BE'], "commune": "107"},
    "Ecole-Militaire": {"sections": ['BF', 'BG', 'BH', 'BI', 'BJ', 'BK', 'BL', 'BM', 'BN',
                        'BO', 'BP', 'BQ', 'BR', 'BS', 'BT'], "commune": "107"},
    "Gros-Caillou": {"sections": ['BU', 'BV', 'BW', 'BX', 'BY', 'BZ', 'CD', 'CE', 'CF',
                     'CG', 'CH', 'CI', 'CJ', 'CK', 'CL', 'CM', 'CN', 'CO',
                     'CP', 'CQ', 'CR', 'CS'], "commune": "107"},
    "Champs-Elysées": {"sections": ['AB', 'AC', 'AD', 'AE', 'AF', 'AG', 'AH', 'AI',
                             'AJ', 'AK', 'AL', 'AM', 'AN', 'AO', 'AP',
                             'AQ', 'AR', 'AS', 'AT'], "commune": "108"},
    "Faubourg-du-Roule": {"sections": ['AU', 'AV', 'AW', 'AX', 'AY', 'AZ', 'BC', 'BD',
                          'BE', 'BF', 'BG', 'BH', 'BI'], "commune": "108"},
    "Madeleine": {"sections": ['BJ', 'BK', 'BL', 'BM', 'BN', 'BO', 'BP', 'BQ', 'BR',
                  'BS', 'BT', 'BU'], "commune": "108"},
    "Europe": {"sections": ['BV', 'BW', 'BX', 'BY', 'BZ', 'CD', 'CE', 'CF', 'CG',
               'CH', 'CI', 'CJ', 'CK', 'CL', 'CM', 'CN', 'CO'], "commune": "108"},
    "Saint-Georges": {"sections": ['AA', 'AB', 'AC', 'AD', 'AE', 'AF', 'AG', 'AH', 'AI',
                      'AJ', 'AK'], "commune": "109"},
    "Chaussée-d'Antin": {"sections": ['AL', 'AM', 'AN', 'AO', 'AP', 'AQ', 'AR', 'AS', 'AT'], "commune": "109"},
    "Faubourg-Montmartre": {"sections": ['AU', 'AV', 'AW', 'AX', 'AY'], "commune": "109"},
    "Rochechouart": {"sections": ['AZ', 'BA', 'BB', 'BC', 'BD', 'BE', 'BF'], "commune": "109"},
    "Saint-Vincent-de-Paul": {"sections": ['AA', 'AB', 'AC', 'AD', 'AE', 'AF', 'AG', 'AH',
                              'AI', 'AJ', 'AK', 'AL', 'AM', 'AN'], "commune": "110"},
    "Porte-Saint-Denis": {"sections": ['AO', 'AP', 'AQ', 'AR', 'AS', 'AT', 'AU', 'AV',
                          'AW'], "commune": "110"},
    "Porte-Saint-Martin": {"sections": ['AX', 'AY', 'AZ', 'BA', 'BB', 'BC', 'BD', 'BE',
                           'BF', 'BG', 'BH', 'BI'], "commune": "110"},
    "Hôpital-Saint-Louis": {"sections": ['BJ', 'BK', 'BL', 'BM', 'BN', 'BO', 'BP', 'BQ',
                            'BR', 'BS', 'BT', 'BU', 'BV', 'BW', 'BX', 'BY'], "commune": "110"},
    "Folie-Méricourt": {"sections": ['AA', 'AB', 'AC', 'AD', 'AE', 'AH', 'AI', 'AK', 'AL',
                        'AM', 'AN', 'AO'], "commune": "111"},
    "Saint-Ambroise": {"sections": ['AP', 'AQ', 'AR', 'AS', 'AT', 'AU', 'AV', 'AW', 'AX',
                       'AY', 'AZ', 'BA', 'BB', 'BC', 'BD', 'BE'], "commune": "111"},
    "Roquette": {"sections": ['BH', 'BI', 'BK', 'BL', 'BM', 'BN', 'BO', 'BP', 'BR', 'BS',
                 'BT', 'BU', 'BV', 'BW', 'BX', 'BY', 'BZ', 'CA', 'CB', 'CC',
                 'CD'], "commune": "111"},
    "Sainte-Marguerite": {"sections": ['CE', 'CH', 'CI', 'CJ', 'CK', 'CL', 'CM', 'CN', 'CO',
                          'CP', 'CR', 'CS', 'CT', 'CV'], "commune": "111"},
    "Bel-Air": {"sections": ['AA', 'AB', 'AC', 'AD', 'AE', 'AH', 'AI', 'AJ', 'AK', 'AL',
                'AM', 'AN', 'AO', 'AP', 'AR', 'AS', 'AT', 'AV', 'AW', 'AX',
                'AY', 'AZ', 'BA', 'BB', 'BC', 'BD'], "commune": "112"},
    "Picpus": {"sections": ['BE', 'BH', 'BK', 'BI', 'BL', 'BM', 'BN', 'BO', 'BP', 'BR',
               'BS', 'BT', 'BV', 'BW', 'BX', 'BY', 'BZ', 'CA', 'CB', 'CC',
               'CD', 'CE', 'CH', 'CI', 'CK', 'CL', 'CM', 'CN', 'CO', 'CP',
               'CR', 'CS', 'CT', 'CV'], "commune": "112"},
    "Bercy": {"sections": ['CW', 'CX', 'CY', 'CZ', 'DA', 'DB', 'DC', 'DD', 'DE', 'DH',
              'DJ', 'DK', 'DL', 'DM', 'DN', 'DO', 'DP', 'DR', 'DS', 'DT',
              'DV', 'DW', 'DX', 'DY', 'DZ', 'EA', 'EB', 'EC', 'ED'], "commune": "112"},
    "Quinze-Vingts": {"sections": ['EE', 'EH', 'EI', 'EK', 'EL', 'EM', 'EN', 'EO',
                      'EP', 'ER', 'ES', 'ET', 'EV', 'EW', 'EX', 'EY',
                      'EZ', 'HA', 'HB', 'HC'], "commune": "112"},
    "Salpêtrière": {"sections": ['AA', 'AB', 'AC', 'AD', 'AE', 'AF', 'AG', 'AH', 'AI',
                    'AJ', 'AK', 'AL', 'AM', 'AN', 'AO', 'AP', 'AQ', 'AR',
                    'AS', 'AT', 'AU', 'AV', 'AW', 'AX'], "commune": "113"},
    "Gare": {"sections": ['AY', 'AZ', 'BA', 'BB', 'BC', 'BD', 'BE', 'BF', 'BG', 'BH',
             'BI', 'BJ', 'BK', 'BL', 'BM', 'BN', 'BO', 'BP', 'BQ', 'BR',
             'BS', 'BT', 'BU', 'BV', 'BW', 'BX', 'BY', 'BZ', 'CA', 'CB',
             'CC', 'CD', 'CE', 'CF', 'CG', 'CH', 'CI', 'CJ', 'CK', 'CL',
             'CM', 'CN', 'CO', 'CP', 'CQ', 'CR', 'CS', 'CT', 'CU', 'CV',
             'CW', 'CX'], "commune": "113"},
    "Maison-Blanche": {"sections": ['CY', 'CZ', 'DA', 'DB', 'DC', 'DD', 'DE', 'DF',
                       'DG', 'DH', 'DI', 'DJ', 'DK', 'DL', 'DM', 'DN',
                       'DO', 'DP', 'DQ', 'DR', 'DS', 'DT', 'DU', 'DV',
                       'DW', 'DX', 'DY', 'DZ', 'EA', 'EB', 'EC', 'ED',
                       'EE', 'EF', 'EG', 'EH', 'EI'], "commune": "113"},
    "Croulebarbe": {"sections": ['EJ', 'EK', 'EL', 'EM', 'EN', 'EO', 'EP', 'EQ',
                    'ER', 'ES', 'ET', 'EU', 'EV'], "commune": "113"},
    "Montparnasse": {"sections": ['AB', 'AC', 'AD', 'AE', 'AF', 'AG', 'AH', 'AI', 'AJ',
                     'AK', 'AL', 'AM', 'AN', 'AO', 'AP', 'AQ', 'AR',
                     'AS'], "commune": "114"},
    "Parc-de-Montsouris": {"sections": ['AT', 'AU', 'AV', 'AW', 'AX', 'AY', 'AZ', 'BC',
                           'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BK',
                           'BL', 'BM', 'BN', 'BO', 'BP'], "commune": "114"},
    "Petit-Montrouge": {"sections": ['BQ', 'BR', 'BS', 'BT', 'BU', 'BV', 'BW', 'BX', 'BY',
                        'BZ', 'CD', 'CE', 'CF', 'CG', 'CH', 'CI', 'CJ', 'CK',
                        'CL', 'CM'], "commune": "114"},
    "Plaisance": {"sections": ['CN', 'CO', 'CP', 'CQ', 'CR', 'CS', 'CT', 'CU', 'CV', 'CW',
                  'CX', 'CY', 'CZ', 'DA', 'DB', 'DC', 'DD', 'DE', 'DF', 'DG',
                  'DH', 'DI', 'DJ', 'DK', 'DL', 'DM', 'DN', 'DO', 'DP', 'DQ',
                  'DR', 'DS', 'DT'], "commune": "114"},
    "Saint-Lambert": {"sections": ['AA', 'AB', 'AC', 'AD', 'AE', 'AF', 'AG', 'AH', 'AI',
                      'AJ', 'AK', 'AL', 'AM', 'AN', 'AO', 'AP', 'AQ', 'AR',
                      'AS', 'AT', 'AU', 'AV', 'AW', 'AX', 'AY', 'AZ', 'BA',
                      'BB', 'BC', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ',
                      'BK', 'BL', 'BM', 'BN', 'BO', 'BP', 'BQ', 'BR', 'BS',
                      'BT', 'BU', 'BV', 'BW'], "commune": "115"},
    "Necker": {"sections": ['BX', 'BY', 'BZ', 'CD', 'CE', 'CF', 'CG', 'CH', 'CI', 'CJ',
               'CK', 'CL', 'CM', 'CN', 'CO', 'CP', 'CQ', 'CR', 'CS', 'CT',
               'CU', 'CV', 'CW', 'CX', 'CY', 'CZ'], "commune": "115"},
    "Grenelle": {"sections": ['DE', 'DF', 'DG', 'DH', 'DI', 'DJ', 'DK', 'DL', 'DM', 'DN',
                 'DO', 'DP', 'DQ', 'DR', 'DS', 'DT', 'DU', 'DV', 'DW', 'DX',
                 'DY', 'DZ', 'EF', 'EG', 'EH'], "commune": "115"},
    "Javel": {"sections": ['EI', 'EJ', 'EK', 'EL', 'EM', 'EN', 'EO', 'EP', 'EQ', 'ER',
              'ES', 'ET', 'EU', 'EV', 'EW', 'EX', 'EY', 'EZ', 'FG', 'FH', 'FI',
              'FJ', 'FK', 'FL', 'FM', 'FN', 'FO', 'FP', 'FQ', 'FR', 'FS', 'FT',
              'FU', 'FV', 'FW', 'FX', 'FY', 'FZ', 'GH', 'GI', 'GJ'], "commune": "115"},
    "Auteuil": {"sections": ['AA', 'AB', 'AC', 'AD', 'AE', 'AF', 'AG', 'AH', 'AI', 'AJ',
                'AK', 'AL', 'AM', 'AN', 'AO', 'AP', 'AQ', 'AR', 'AS', 'AT',
                'AU', 'AV', 'AW', 'AX', 'AY', 'AZ', 'BA', 'BB', 'BC', 'BD',
                'BE', 'BF', 'BM', 'BN', 'BO', 'BP', 'BQ', 'BR', 'BS', 'BT',
                'BU', 'BV', 'BW', 'BX', 'BY', 'BZ', 'CA', 'CB'], "commune": "116"},
    "Muette": {"sections": ['CC', 'CD', 'CE', 'CF', 'CG', 'CH', 'CI', 'CJ', 'CK', 'CL',
               'CM', 'CN', 'CO', 'CP', 'CQ', 'CR', 'CS', 'CT', 'DD', 'DE',
               'DF', 'DG', 'DH', 'DI', 'DJ', 'DK', 'DL', 'DM', 'DN', 'DO',
               'DP', 'DQ', 'DR', 'DS', 'DT'], "commune": "116"},
    "Porte-Dauphine": {"sections": ['DU', 'DV', 'DW', 'DX', 'DY', 'DZ', 'EA', 'EB', 'EC',
                       'ED', 'EE', 'EF', 'EG', 'EH', 'EI', 'EJ', 'EK', 'ER',
                       'ES', 'ET', 'EU', 'EV', 'EW', 'EX', 'EY'], "commune": "116"},
    "Chaillot": {"sections": ['EZ', 'FA', 'FB', 'FC', 'FD', 'FE', 'FF', 'FG', 'FH', 'FI',
                 'FJ', 'FK', 'FL', 'FM', 'FN', 'FO', 'FP', 'FQ', 'FR', 'FS',
                 'FT', 'FU'], "commune": "116"},
    "Ternes": {"sections": ['AA', 'AB', 'AC', 'AD', 'AE', 'AF', 'AG', 'AH', 'AI', 'AJ',
               'AK', 'AL', 'AM', 'AN', 'AO', 'AP', 'AQ', 'AR', 'AS', 'AT',
               'AU', 'AV', 'AW', 'AX', 'AY', 'AZ', 'BA'], "commune": "117"},
    "Plaine de Monceaux": {"sections": ['BB', 'BC', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI',
                           'BJ', 'BK', 'BL', 'BM', 'BN', 'BO', 'BP', 'BQ',
                           'BR', 'BS', 'BT', 'BU', 'BV', 'BW', 'BX', 'BY'], "commune": "117"},
    "Batignolles": {"sections": ['BZ', 'CA', 'CB', 'CC', 'CD', 'CE', 'CF', 'CG', 'CH',
                    'CI', 'CJ', 'CK', 'CL', 'CM', 'CN', 'CO', 'CP', 'CQ',
                    'CR', 'CS', 'CT', 'CU', 'CV', 'CW', 'CX'], "commune": "117"},
    "Epinettes": {"sections": ['CY', 'CZ', 'DA', 'DB', 'DC', 'DD', 'DE', 'DF', 'DG', 'DH',
                  'DI', 'DJ', 'DK', 'DL', 'DM', 'DN', 'DO', 'DP', 'DQ', 'DR',
                  'DS'], "commune": "117"},
    "Grandes-Carrières": {"sections": ['AA', 'AB', 'AC', 'AD', 'AE', 'AF', 'AG', 'AH', 'AI',
                          'AJ', 'AK', 'AL', 'AM', 'AN', 'AO', 'AP', 'AQ', 'AR',
                          'AS', 'AT', 'AU', 'AV', 'AW', 'AX', 'AY', 'AZ',
                          'BA'], "commune": "118"},
    "Clignancourt": {"sections": ['BB', 'BC', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ',
                     'BK', 'BL', 'BM', 'BN', 'BO', 'BP', 'BQ', 'BR', 'BS',
                     'BT', 'BU', 'BV', 'BW', 'BX', 'BY', 'BZ'], "commune": "118"},
    "Goutte-d'Or": {"sections": ['CA', 'CB', 'CC', 'CD', 'CE', 'CF', 'CG', 'CH',
                    'CI', 'CJ', 'CK', 'CL', 'CM', 'CN', 'CO', 'CP'], "commune": "118"},
    "La Chapelle": {"sections": ['CQ', 'CR', 'CS', 'CT', 'CU', 'CV', 'CW', 'CX',
                    'CY', 'CZ', 'DA', 'DB', 'DC', 'DD', 'DE', 'DF'], "commune": "118"},
    "Villette": {"sections": ['AA', 'AB', 'AC', 'AD', 'AE', 'AF', 'AG', 'AH', 'AI',
                 'AJ', 'AK', 'AL', 'AM', 'AN', 'AO', 'AP', 'AQ', 'AR',
                 'AS', 'AT', 'AU', 'AV', 'AW', 'AX', 'AY', 'AZ',
                 'BA'], "commune": "119"},
    "Pont-de-Flandre": {"sections": ['BB', 'BC', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI',
                        'BJ', 'BK', 'BL', 'BM', 'BN', 'BO', 'BP', 'BQ',
                        'BR', 'BS', 'BT', 'BU', 'BV', 'BW', 'BX', 'BY',
                        'BZ', 'CB', 'CC', 'CD', 'CE', 'CF', 'CG', 'CH',
                        'CI', 'CJ', 'CK', 'CL', 'CM', 'CN', 'CO', 'CP',
                        'CQ', 'CR', 'CS'], "commune": "119"},
    "Amérique": {"sections": ['CT', 'CU', 'CV', 'CW', 'CX', 'CY', 'CZ', 'DA', 'DB',
                 'DC', 'DD', 'DE', 'DF', 'DG', 'DH', 'DI', 'DJ', 'DK',
                 'DL', 'DM', 'DN', 'DO', 'DP', 'DQ', 'DR', 'DS', 'DT',
                 'DU', 'DV', 'DW', 'DX', 'DY', 'DZ', 'EA'], "commune": "119"},
    "Combat": {"sections": ['EB', 'EC', 'ED', 'EE', 'EF', 'EG', 'EH', 'EI', 'EJ', 'EK',
               'EL', 'EM', 'EN', 'EO', 'EP', 'EQ', 'ER', 'ES', 'ET', 'EU',
               'EV', 'EW', 'EX'], "commune": "119"},
    "Belleville": {"sections": ['AA', 'AB', 'AC', 'AD', 'AE', 'AF', 'AG', 'AH', 'AI',
                   'AJ', 'AK', 'AL', 'AM', 'AN', 'AO', 'AP', 'AQ', 'AR'], "commune": "120"},
    "Saint-Fargeau": {"sections": ['AS', 'AT', 'AU', 'AV', 'AW', 'AX', 'AY', 'AZ',
                      'BA', 'BB', 'BC', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI',
                      'BJ', 'BK', 'BL', 'BM', 'BN', 'BO', 'BP', 'BQ',
                      'BR', 'BS'], "commune": "120"},
    "Père-Lachaise": {"sections": ['BT', 'BU', 'BV', 'BW', 'BX', 'BY', 'BZ', 'CA', 'CB',
                      'CC', 'CD', 'CE', 'CF', 'CG', 'CH', 'CI', 'CJ', 'CK',
                      'CL', 'CM', 'CN', 'CO', 'CP', 'CQ', 'CR', 'CS', 'CT'], "commune": "120"},
    "Charonne": {"sections": ['CV', 'CW', 'CX', 'CY', 'CZ', 'DA', 'DB', 'DC', 'DD', 'DE',
                 'DF', 'DG', 'DH', 'DI', 'DJ', 'DK', 'DL', 'DM', 'DN', 'DO',
                 'DP', 'DQ', 'DR', 'DS', 'DT', 'DU', 'DV', 'DW', 'DX', 'DY',
                 'DZ', 'EA', 'EB', 'EC', 'ED'], "commune": "120"}
}
